src/polling_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),

]

src/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionView.as_view(), name='question'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/',views.vote, name='vote')
]

src/polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) -> str:
        return self.question_text

    def was_published_recently(self) -> bool:
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text
    
    

src/polls/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import F
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.
from .models import Question

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self) -> list[Question]:
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class QuestionView(generic.DetailView):
    # model = Question
    template_name = "polls/question.html"

    def get_queryset(self) -> QuerySet[Any]:
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"



def index(request: HttpRequest ) -> HttpResponse:
    # return HttpResponse("Hello, world. You're at the polls index.")
    questions = Question.objects.order_by("-pub_date")[:5]
    # set context
    context = {
        "latest_question_list": questions
    }
    ## method 1 using loader and loader.render

    # template = loader.get_template('polls/index.html')
    # response = template.render(context, request)
    ## method 2 using render

    response = render(request, "polls/index.html", context)

    return response


def question(request: HttpRequest, question_id: int) -> HttpResponse: 
    ## method 1 using try except
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404(f"Question with id = {question_id} does not exist.")

    ## method 2 using get_object_or_404
    question = get_object_or_404(Question, pk=question_id)

    
    return HttpResponse(render(request, "polls/question.html", {"question":question}))

def results(request: HttpRequest, question_id: int) -> HttpResponse:

    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/results.html", {"question": question})


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST["choice"]
        )
    except KeyError:
        return render(request, "polls/question.html", {
            "question": question,
            "error_message": "You didn't select a choice."
        })
    else:
        selected_choice.votes = F("votes") +1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results",
                                            args=(question.id,)))

src/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-gray-100">
    <div class="container mx-auto">
        <h2 class="text-2xl font-bold mb-4"> Questions<h2>
    <div>
<div class="container mx-auto p-4">
    {% if latest_question_list %}
    <ul class="space-y-1">
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:question' question.id %}" class="text-blue-500 hover:underline">{{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
</body>

</html>

src/polls/templates/polls/question.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <legend>
            <h1 class="text-3xl font-bold mb-4">{{ question }}</h1>
        </legend>

            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice }}</label><br>
            {% endfor %}
            <fieldset>
                <input type="submit" value="vote">
            </fieldset>


    </form>
</body>
</html>

src/polls/templates/polls/results.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <h1 class="text-3xl font-bold mb-4">{{ question }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <div>
        <a href="{% url 'polls:question' question.id %}">Vote again?</a> 
    </div>
    <div>
        <a href="{% url 'polls:index' %}">Go back to Polls Home</a>

    </div>

   
</body>
</html>